version: "1.0"
services:
  aggregator:
    build:
      context: .
      dockerfile: Dockerfile
    image: uts-aggregator:latest
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - DEDUP_DB_PATH=/app/data/dedup.db
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/health', timeout=2)"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
    restart: unless-stopped

  publisher:
    build:
      context: .
      dockerfile: publisher.Dockerfile
    image: uts-publisher:latest
    depends_on:
      aggregator:
        condition: service_healthy
    environment:
      - AGG_URL=http://aggregator:8080/publish
      - COUNT=5000
      - UNIQUE=4000
      - BATCH=500
      - CONC=4
    restart: on-failure
